#!/usr/bin/env python3
"""
Machining exports: DXF profiles, plus a plain statement of what is NOT here.

WHAT A MACHINE SHOP ACTUALLY WANTS IS STEP, AND THIS CANNOT PRODUCE IT.
STEP is a boundary representation - real surfaces, exact arcs, named faces. The
geometry in this repo is a triangle mesh, because trimesh is a mesh library and
the parts were authored for a printer. Converting mesh to STEP does not recover
what was never there: you get a solid made of thousands of triangular facets,
which imports, looks right, and is miserable to machine from - every "cylinder"
is a polygon and the toolpath chatters round it.

The honest routes to STEP, in order of how good the result is:

  1. Rebuild from cad/nano.py's P dict in a parametric CAD tool. Every
     dimension is a named number in one place at the top of that file, and the
     part functions read as a recipe. Half a day for a competent CAD operator
     and the output is proper B-rep.
  2. Import the STL into Fusion 360 / FreeCAD and convert to solid. Fast,
     faceted, adequate for a one-off.
  3. Ask for the printed parts and reverse-engineer. Slowest, and the printed
     part already carries the FDM compensation baked into the model.

What this script does produce is genuinely useful for the flat work: true
outlines through any part at any height, as DXF, for laser, waterjet or a 2D
profile cut. Those are exact - a section through a mesh is a real polygon, not
an approximation of one.
"""
import os, sys
import numpy as np
import trimesh
import ezdxf

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
# Everything a client needs, in one obvious place at the repo root. Scattering
# STL under nano/, OBJ under cad/export/ and plates under nano/plates/ is fine
# for whoever wrote it and hostile to whoever was sent the link. MODELS/ is
# uppercase so it sorts to the top of the GitHub file listing and is the first
# thing a visitor sees.
MODELS = os.path.join(ROOT, "MODELS")
OUT = os.path.join(MODELS, "DXF")
os.makedirs(OUT, exist_ok=True)

# (part, height to section at, why that height)
CUTS = [
    ("deck",       1.25, "mid-plate: the true outline plus every slot and bore"),
    ("case_lower", 0.70, "footprint and wall line at the first layer"),
    ("case_upper", 0.70, "lid outline, mouth and the OLED window"),
    ("drawer",     9.00, "bin walls at mid height"),
    ("pinion",     3.00, "gear tooth profile, exact involute"),
]


def section_dxf(name, z, note):
    p = os.path.join(ROOT, "nano", name + ".stl")
    if not os.path.exists(p):
        print("  %-12s no STL" % name); return
    m = trimesh.load(p)
    z_abs = m.bounds[0][2] + z
    sec = m.section(plane_origin=[0, 0, z_abs], plane_normal=[0, 0, 1])
    if sec is None:
        print("  %-12s nothing at z=%.2f" % (name, z)); return
    pl, _ = sec.to_2D()
    doc = ezdxf.new("R2010")
    doc.header["$INSUNITS"] = 4          # millimetres, so CAM does not guess
    msp = doc.modelspace()
    n = 0
    for poly in pl.polygons_full:
        msp.add_lwpolyline(list(poly.exterior.coords), close=True)
        n += 1
        for ring in poly.interiors:
            msp.add_lwpolyline(list(ring.coords), close=True)
            n += 1
    out = os.path.join(OUT, "%s_z%.2f.dxf" % (name, z))
    doc.saveas(out)
    print("  %-12s z=%5.2f  %2d loops  ->  %s" % (name, z, n, os.path.basename(out)))


def populate_models():
    """Copy every shipped part into MODELS/, in each format.

    Copies rather than symlinks: GitHub does not serve a symlink as a
    downloadable file, and a client clicking Download would get a text file
    containing a path. Regenerated by this script, so the two cannot drift
    without somebody noticing the diff."""
    import glob, shutil
    made = {}
    for sub, pat, src in (("STL", "*.stl", os.path.join(ROOT, "nano")),
                          ("PLATES-3MF", "*.3mf", os.path.join(ROOT, "nano", "plates"))):
        d = os.path.join(MODELS, sub); os.makedirs(d, exist_ok=True)
        n = 0
        for f in sorted(glob.glob(os.path.join(src, pat))):
            if "copy" in os.path.basename(f):
                continue
            shutil.copy2(f, os.path.join(d, os.path.basename(f))); n += 1
        made[sub] = n
    d = os.path.join(MODELS, "OBJ"); os.makedirs(d, exist_ok=True)
    n = 0
    for f in sorted(glob.glob(os.path.join(ROOT, "nano", "*.stl"))):
        if "copy" in os.path.basename(f):
            continue
        trimesh.load(f).export(os.path.join(
            d, os.path.basename(f).replace(".stl", ".obj")))
        n += 1
    made["OBJ"] = n
    return made


if __name__ == "__main__":
    print("\nDXF profiles (millimetres, R2010)\n")
    for name, z, note in CUTS:
        section_dxf(name, z, note)
    print("\n  STEP is not produced here - see the module docstring for why")
    print("  and for the three honest routes to it.")
    print()
    for k, v in populate_models().items():
        print("  MODELS/%-12s %2d files" % (k, v))
    print("  -> %s" % MODELS)
